[package]
name = "c0c"
version = "0.1.0"
authors = ["Nick Maus <nmausv@gmail.com>"]

[dependencies]
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }

# Add a build-time dependency on the lalrpop library:
[build-dependencies]
lalrpop = "0.22.0"

